version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3020:3020'
        environment:
            - PORT=3020
            - DB_URL=mongodb+srv://reguler_access:16101191@cluster0.5xh4g.mongodb.net/scheduling_app?retryWrites=true&w=majority
            - SECRET=FDxcz7+72saAFc
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: db_name
            MONGO_INITDB_ROOT_USERNAME: name
            MONGO_INITDB_ROOT_PASSWORD: pass
